.styleci.yml
=> Enable Styleci

composer.json
Avoid commit noise while updating `composer.json`
=> Avoid noise while updating composer.json

.travis.yml, composer.json
Install phpunit dependency and use while testing
=> Install phpunit dependency and use while testing

src/Identicon/Generator/BaseGenerator.php, src/Identicon/Generator/GdGenerator.php, src/Identicon/Generator/ImageMagickGenerator.php
=> Remove some useless imports

src/Identicon/Generator/BaseGenerator.php
=> Fix return docblocks

src/autoload.php
=> Remove useless variable

composer.json
* Update `fzaninotto/faker` to `^1.2.0`
* Sort `require-dev`
=> Sort require-dev

src/Identicon/Generator/ImageMagickGenerator.php, src/Identicon/Generator/SvgGenerator.php, src/Identicon/Identicon.php, src/autoload.php
=> Ensure code respects PSR2

src/Identicon/Generator/BaseGenerator.php, src/Identicon/Generator/GdGenerator.php, src/Identicon/Generator/ImageMagickGenerator.php
Imports some classes and exceptions
=> Imports some classes and exceptions

.gitattributes
Avoid the export of some files and folders.
Also set `* text=auto`
=> Avoid the export of some files and folders

src/Identicon/Generator/BaseGenerator.php
=> Use integers for array keys

src/Identicon/Generator/BaseGenerator.php, src/Identicon/Generator/GdGenerator.php, src/Identicon/Generator/ImageMagickGenerator.php, src/Identicon/Generator/SvgGenerator.php, src/Identicon/Identicon.php
=> Fix some docblocks

src/Identicon/Generator/BaseGenerator.php
=> Only calculate values once

.styleci.yml
Add more StyleCI fixers
---
Note: https://styleci.io/analyses/XNAPxp can be auto-applied
=> Add more StyleCI fixers

src/Identicon/Generator/BaseGenerator.php, src/Identicon/Generator/GdGenerator.php, src/Identicon/Identicon.php
=> Fix some typo

src/Identicon/Generator/BaseGenerator.php
Simplify `\Identicon\Generator\BaseGenerator::convertColor`
=> Simplify \Identicon\Generator\BaseGenerator::convertColor

README.md
=> Some fixes in readme

.travis.yml
=> Respect editorconfig

src/Identicon/Generator/ImageMagickGenerator.php
Import Exception and fix docblock
https://styleci.io/analyses/8jLZGB can be automerged
=> Import Exception and fix docblock

src/Identicon/Generator/BaseGenerator.php
Factorize convertHashToArrayOfBoolean
https://styleci.io/analyses/Xaj9wx can be automerged
=> Factorize convertHashToArrayOfBoolean

.styleci.yml
=> Ensure imports are ordered

.travis.yml
=> Cache PHP packages

.travis.yml
use latest composer and avoid timeouts
=> use latest composer and avoid timeouts

.travis.yml, composer.json
=> Use --prefer-dist as default

src/Identicon/Generator/BaseGenerator.php, tests/Identicon/Tests/Generator/BaseGeneratorTest.php
Enable short hexadecimal color notation
=> Enable short hexadecimal color notation

.codecov.yml, .gitattributes, .travis.yml, README.md
Provide some code coverage using https://codecov.io
=> Provide some code coverage

.travis.yml
Let phpunit cover code for codecov.
---
The codecov status should ping too.
=> Let phpunit cover code for codecov

src/Identicon/Generator/BaseGenerator.php
Ensure pixel-ratio is handled as an integer.
=> Ensure pixel-ratio is handled as an integer.

src/Identicon/Generator/BaseGenerator.php
=> Fix some alignments

composer.json
=> Switch tests to PSR-4.

src/Identicon/Generator/BaseGenerator.php
=> Fix a docblock.

tests/Identicon/Tests/Generator/BaseGeneratorTest.php
=> Declare a missing property.

src/Identicon/Generator/GeneratorInterface.php, src/Identicon/Identicon.php
Hey, i have added a new getColor() Method to the Identicon object as discussed in issue #52 .
=> Added a getColor() method

.travis.yml
=> Also test PHP 7.1.

src/Identicon/Generator/BaseGenerator.php
=> Remove useless integer cast.
